# Generated by Django 5.2.4 on 2025-08-05 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_inmobiliario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionCaptacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sección de Captación',
                'verbose_name_plural': 'Secciones de Captación',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FormularioCaptacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('observaciones_generales', models.TextField(blank=True, null=True)),
                ('firma_cliente', models.ImageField(blank=True, null=True, upload_to='firmas_captacion/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('is_firmado', models.BooleanField(default=False)),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('tipo_captacion', models.CharField(choices=[('venta', 'Venta'), ('renta', 'Renta')], max_length=10)),
                ('propiedad_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captaciones', to='core_inmobiliario.propiedadcliente')),
            ],
            options={
                'verbose_name': 'Formulario de Captación',
                'verbose_name_plural': 'Formularios de Captación',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='FormularioEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(auto_now_add=True)),
                ('observaciones_generales', models.TextField(blank=True, null=True)),
                ('firma_cliente', models.ImageField(blank=True, null=True, upload_to='firmas/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('is_firmado', models.BooleanField(default=False)),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('propiedad_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_inmobiliario.propiedadcliente')),
            ],
            options={
                'verbose_name': 'Formulario de Entrega',
                'verbose_name_plural': 'Formularios de Entrega',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='AmbienteEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ambiente', models.CharField(choices=[('ALCOBA', 'Alcoba'), ('BAÑO', 'Baño'), ('COCINA', 'Cocina'), ('SALA', 'Sala'), ('COMEDOR', 'Comedor'), ('ZONA_ROPA', 'Zona de Ropa'), ('BALCON', 'Balcón'), ('OTRO', 'Otro')], max_length=20)),
                ('numero_ambiente', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre_personalizado', models.CharField(blank=True, max_length=100, null=True)),
                ('formulario_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambientes', to='inventarioapp.formularioentrega')),
            ],
        ),
        migrations.CreateModel(
            name='ItemBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_ambiente', models.CharField(choices=[('ALCOBA', 'Alcoba'), ('BAÑO', 'Baño'), ('COCINA', 'Cocina'), ('SALA', 'Sala'), ('COMEDOR', 'Comedor'), ('ZONA_ROPA', 'Zona de Ropa'), ('BALCON', 'Balcón'), ('OTRO', 'Otro')], max_length=20)),
                ('nombre_item', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Item Base',
                'verbose_name_plural': 'Items Base',
                'unique_together': {('tipo_ambiente', 'nombre_item')},
            },
        ),
        migrations.CreateModel(
            name='ItemEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_item', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('B', 'Bueno'), ('R', 'Regular'), ('M', 'Malo')], max_length=1)),
                ('cantidad', models.PositiveIntegerField(blank=True, null=True)),
                ('material', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('es_personalizado', models.BooleanField(default=False)),
                ('ambiente_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventarioapp.ambienteentrega')),
            ],
        ),
        migrations.CreateModel(
            name='CampoCaptacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('booleano', 'Sí/No')], max_length=10)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('obligatorio', models.BooleanField(default=False)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='inventarioapp.seccioncaptacion')),
            ],
            options={
                'verbose_name': 'Campo de Captación',
                'verbose_name_plural': 'Campos de Captación',
                'ordering': ['seccion', 'orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ValorCampoCaptacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.TextField(blank=True, null=True)),
                ('valor_numero', models.FloatField(blank=True, null=True)),
                ('valor_booleano', models.BooleanField(blank=True, null=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarioapp.campocaptacion')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='inventarioapp.formulariocaptacion')),
            ],
            options={
                'verbose_name': 'Valor de Campo de Captación',
                'verbose_name_plural': 'Valores de Campos de Captación',
                'unique_together': {('formulario', 'campo')},
            },
        ),
    ]
