# Generated by Django 5.2.4 on 2025-08-15 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioapp', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campocaptacion',
            name='inmobiliaria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usuarios.inmobiliaria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itembase',
            name='inmobiliaria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usuarios.inmobiliaria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seccioncaptacion',
            name='inmobiliaria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usuarios.inmobiliaria'),
            preserve_default=False,
        ),
    ]
