# Generated by Django 5.2.4 on 2025-08-15 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioapp', '0002_campocaptacion_inmobiliaria_itembase_inmobiliaria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campocaptacion',
            name='inmobiliaria',
        ),
    ]
