# Generated by Django 5.2.4 on 2025-08-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmobiliaria',
            name='cedula_firma_autorizada',
            field=models.CharField(blank=True, help_text='Cédula o documento de identidad', max_length=30),
        ),
        migrations.AddField(
            model_name='inmobiliaria',
            name='firma_autorizada',
            field=models.ImageField(blank=True, null=True, upload_to='firmas_inmobiliarias/'),
        ),
        migrations.AddField(
            model_name='inmobiliaria',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_inmobiliarias/'),
        ),
        migrations.AddField(
            model_name='inmobiliaria',
            name='nombre_firma_autorizada',
            field=models.CharField(blank=True, help_text='Nombre del representante autorizado que firma', max_length=150),
        ),
        migrations.AddField(
            model_name='inmobiliaria',
            name='texto_contractual_captacion_renta',
            field=models.TextField(blank=True, default='Texto contractual de captación para renta por defecto...', null=True),
        ),
        migrations.AddField(
            model_name='inmobiliaria',
            name='texto_contractual_captacion_venta',
            field=models.TextField(blank=True, default='Texto contractual de captación para venta por defecto...', null=True),
        ),
        migrations.AddField(
            model_name='inmobiliaria',
            name='texto_contractual_entrega',
            field=models.TextField(blank=True, default='Texto contractual por defecto...', null=True),
        ),
    ]
