# Generated by Django 5.2.4 on 2025-08-25 21:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_inmobiliaria_cedula_firma_autorizada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmobiliaria',
            name='camara_registro',
            field=models.CharField(blank=True, help_text='Cámara de Comercio donde se registró la inmobiliaria', max_length=20),
        ),
        migrations.AddField(
            model_name='inmobiliaria',
            name='ciudad_domicilio',
            field=models.CharField(blank=True, help_text='Ciudad de domicilio de la inmobiliaria', max_length=100),
        ),
        migrations.AddField(
            model_name='inmobiliaria',
            name='fecha_registro',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Fecha de registro de la inmobiliaria en Cámara de Comercio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inmobiliaria',
            name='matricula_arrendador',
            field=models.CharField(blank=True, help_text='Número de resolución de matrícula del arrendador y fecha de expedición', max_length=100),
        ),
        migrations.AddField(
            model_name='inmobiliaria',
            name='numero_registro',
            field=models.CharField(blank=True, help_text='Número de registro de la inmobiliaria en Cámara de Comercio', max_length=20),
        ),
        migrations.AddField(
            model_name='inmobiliaria',
            name='pagina_web',
            field=models.URLField(blank=True, help_text='Página web de la inmobiliaria'),
        ),
    ]
