# Generated by Django 5.2.4 on 2025-09-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_inmobiliaria_camara_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmobiliaria',
            name='forma_recaudo',
            field=models.CharField(blank=True, help_text='Forma de recaudo de la inmobiliaria', max_length=150),
        ),
    ]
