# Generated by Django 5.2.4 on 2025-09-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_inmobiliaria_forma_recaudo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmobiliaria',
            name='camara_registro',
            field=models.CharField(blank=True, help_text='Cámara de Comercio donde se registró la inmobiliaria', max_length=100),
        ),
    ]
