# Generated by Django 5.2.4 on 2025-09-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_inmobiliaria_camara_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmobiliaria',
            name='matricula_arrendador',
            field=models.TextField(blank=True, help_text='Número de resolución de matrícula del arrendador y fecha de expedición'),
        ),
    ]
