# Generated by Django 5.2.4 on 2025-08-24 18:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_inmobiliario', '0001_initial'),
        ('usuarios', '0002_inmobiliaria_cedula_firma_autorizada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionArriendos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_plazo_pago_defecto', models.PositiveIntegerField(default=5, help_text='Plazo por defecto (en días) que se usará al crear nuevos contratos.')),
                ('cobra_iva_comision', models.BooleanField(default=True, help_text='Indica si se debe calcular y añadir el IVA sobre la comisión de la inmobiliaria.')),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=19.0, help_text='El porcentaje de IVA a aplicar (ej. 19.00 para 19%).', max_digits=5)),
                ('requiere_factura_electronica', models.BooleanField(default=False, help_text='Activar si la inmobiliaria está obligada a emitir factura electrónica.')),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('inmobiliaria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_arriendos', to='usuarios.inmobiliaria')),
            ],
        ),
        migrations.CreateModel(
            name='ContratoArrendamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='VIGENTE', max_length=20)),
                ('periodicidad', models.CharField(choices=[('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='MENSUAL', max_length=20)),
                ('uso_inmueble', models.CharField(choices=[('VIVIENDA', 'Vivienda'), ('COMERCIAL', 'Comercial')], max_length=20)),
                ('renovacion_automatica', models.BooleanField(default=True)),
                ('meses_preaviso', models.PositiveIntegerField(default=3, help_text='Meses de antelación para notificar la renovación/terminación.')),
                ('tipo_incremento', models.CharField(choices=[('IPC', 'Basado en IPC'), ('PORCENTAJE_FIJO', 'Porcentaje Fijo'), ('IPC_MAS_PUNTOS', 'IPC + Puntos Adicionales')], default='IPC', max_length=20)),
                ('valor_incremento', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje o puntos a añadir al IPC.', max_digits=5)),
                ('observaciones', models.TextField(blank=True)),
                ('clausulas_adicionales', models.TextField(blank=True)),
                ('texto_final_renderizado', models.TextField(editable=False, help_text='El texto final del contrato tal como se firmó, para integridad legal.')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('dias_plazo_pago', models.PositiveIntegerField(default=5)),
                ('prorrateado', models.BooleanField(default=False, help_text='Indica si el primer pago corresponde a una fracción del mes.')),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_inmobiliario.cliente')),
                ('inmobiliaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.inmobiliaria')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_inmobiliario.propiedad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CargoAdicionalArrendatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Cobro'), ('COBRADO', 'Cobrado')], default='PENDIENTE', max_length=20)),
                ('contrato_arrendamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos_adicionales', to='gestion_arriendos.contratoarrendamiento')),
            ],
        ),
        migrations.CreateModel(
            name='ContratoMandato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='VIGENTE', max_length=20)),
                ('periodicidad', models.CharField(choices=[('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral'), ('ANUAL', 'Anual')], default='MENSUAL', max_length=20)),
                ('uso_inmueble', models.CharField(choices=[('VIVIENDA', 'Vivienda'), ('COMERCIAL', 'Comercial')], max_length=20)),
                ('renovacion_automatica', models.BooleanField(default=True)),
                ('meses_preaviso', models.PositiveIntegerField(default=3, help_text='Meses de antelación para notificar la renovación/terminación.')),
                ('tipo_incremento', models.CharField(choices=[('IPC', 'Basado en IPC'), ('PORCENTAJE_FIJO', 'Porcentaje Fijo'), ('IPC_MAS_PUNTOS', 'IPC + Puntos Adicionales')], default='IPC', max_length=20)),
                ('valor_incremento', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje o puntos a añadir al IPC.', max_digits=5)),
                ('observaciones', models.TextField(blank=True)),
                ('clausulas_adicionales', models.TextField(blank=True)),
                ('texto_final_renderizado', models.TextField(editable=False, help_text='El texto final del contrato tal como se firmó, para integridad legal.')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dia_corte_liquidaciones', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('asumir_impuestos', models.BooleanField(default=False)),
                ('inmobiliaria_paga_administracion', models.BooleanField(default=True, help_text='Marca esta casilla si en el acuerdo la inmobiliaria es responsable de pagar la administración.')),
                ('inmobiliaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.inmobiliaria')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_inmobiliario.propiedad')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_inmobiliario.cliente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contratoarrendamiento',
            name='contrato_mandato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_arrendamiento', to='gestion_arriendos.contratomandato'),
        ),
        migrations.CreateModel(
            name='DescuentoNoProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('numero_cuotas', models.PositiveIntegerField(default=1)),
                ('fecha_reporte', models.DateField()),
                ('contrato_mandato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos_no_programados', to='gestion_arriendos.contratomandato')),
                ('inmobiliaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.inmobiliaria')),
            ],
        ),
        migrations.CreateModel(
            name='CuotaDescuentoNoProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('valor_cuota', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Aplicar'), ('APLICADO', 'Aplicado en Liquidación')], default='PENDIENTE', max_length=20)),
                ('descuento_no_programado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='gestion_arriendos.descuentonoprogramado')),
            ],
            options={
                'verbose_name': 'Cuota de Descuento No Programado',
                'verbose_name_plural': 'Cuotas de Descuentos No Programados',
                'unique_together': {('descuento_no_programado', 'mes', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='DescuentoProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('contrato_mandato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos_programados', to='gestion_arriendos.contratomandato')),
                ('inmobiliaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.inmobiliaria')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialValorDescuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_inicio_vigencia', models.DateField()),
                ('descuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_valores', to='gestion_arriendos.descuentoprogramado')),
            ],
            options={
                'ordering': ['-fecha_inicio_vigencia'],
            },
        ),
        migrations.CreateModel(
            name='IPCAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(unique=True)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor porcentual del IPC (ej. 5.62 para 5.62%)', max_digits=5)),
                ('inmobiliaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.inmobiliaria')),
            ],
        ),
        migrations.CreateModel(
            name='PlantillaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_contrato', models.CharField(choices=[('MANDATO', 'Mandato con Propietario'), ('ARRENDAMIENTO', 'Arrendamiento con Inquilino')], max_length=20)),
                ('cuerpo_texto', models.TextField(help_text='Cuerpo de la plantilla. Usa variables como {{cliente_nombre}}.')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('inmobiliaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.inmobiliaria')),
            ],
        ),
        migrations.AddField(
            model_name='contratomandato',
            name='plantilla_usada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_arriendos.plantillacontrato'),
        ),
        migrations.AddField(
            model_name='contratoarrendamiento',
            name='plantilla_usada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_arriendos.plantillacontrato'),
        ),
        migrations.CreateModel(
            name='RegistroDescuentoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('valor', models.DecimalField(decimal_places=2, help_text='El valor que tenía el descuento en este mes específico.', max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Aplicar'), ('APLICADO', 'Aplicado en Liquidación')], default='PENDIENTE', max_length=20)),
                ('descuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_arriendos.descuentoprogramado')),
            ],
            options={
                'verbose_name': 'Registro Mensual de Descuento',
                'verbose_name_plural': 'Registros Mensuales de Descuentos',
                'unique_together': {('descuento', 'mes', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='VigenciaContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INICIAL', 'Vigencia Inicial'), ('RENOVACION', 'Renovación')], default='INICIAL', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('valor_canon', models.DecimalField(decimal_places=2, help_text='Valor total que paga el arrendatario, incluida la administración si aplica.', max_digits=12)),
                ('contrato_arrendamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vigencias', to='gestion_arriendos.contratoarrendamiento')),
            ],
            options={
                'verbose_name': 'Vigencia de Contrato',
                'verbose_name_plural': 'Vigencias de Contrato',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_liquidado', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('anio_liquidado', models.PositiveIntegerField()),
                ('valor_arriendo_cobrado', models.DecimalField(decimal_places=2, help_text='Canon cobrado al arrendatario en este período.', max_digits=12)),
                ('total_descuentos_programados', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_descuentos_no_programados', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_comision', models.DecimalField(decimal_places=2, max_digits=12)),
                ('iva_comision', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_a_pagar', models.DecimalField(decimal_places=2, help_text='El valor final a pagar al propietario.', max_digits=12)),
                ('pagada', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('contrato_mandato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='gestion_arriendos.contratomandato')),
                ('descuentos_no_programados_aplicados', models.ManyToManyField(blank=True, related_name='liquidaciones', to='gestion_arriendos.cuotadescuentonoprogramado')),
                ('inmobiliaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.inmobiliaria')),
                ('descuentos_programados_aplicados', models.ManyToManyField(blank=True, related_name='liquidaciones', to='gestion_arriendos.registrodescuentomensual')),
            ],
            options={
                'verbose_name': 'Liquidación Mensual',
                'verbose_name_plural': 'Liquidaciones Mensuales',
                'unique_together': {('contrato_mandato', 'mes_liquidado', 'anio_liquidado')},
            },
        ),
        migrations.CreateModel(
            name='RegistroCobroMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveIntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('valor_canon', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Facturar'), ('FACTURADO', 'Facturado'), ('PAGADO', 'Pagado'), ('EN_MORA', 'En Mora')], default='PENDIENTE', max_length=20)),
                ('vigencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_arriendos.vigenciacontrato')),
            ],
            options={
                'unique_together': {('vigencia', 'mes', 'anio')},
            },
        ),
    ]
