# Generated by Django 5.2.4 on 2025-08-25 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_inmobiliario', '0002_propiedad_escritura_publica_cuentabancaria'),
        ('gestion_arriendos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratomandato',
            name='cuenta_bancaria_pago',
            field=models.ForeignKey(default=1, help_text='Cuenta bancaria donde se consignará el pago al propietario.', on_delete=django.db.models.deletion.PROTECT, to='core_inmobiliario.cuentabancaria'),
            preserve_default=False,
        ),
    ]
