# Generated by Django 5.2.4 on 2025-08-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_arriendos', '0002_contratomandato_cuenta_bancaria_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratoarrendamiento',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('FINALIZADO', 'Finalizado (Pendiente de Firma)'), ('VIGENTE', 'Vigente (Firmado y Activo)'), ('TERMINADO', 'Terminado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='contratoarrendamiento',
            name='texto_final_renderizado',
            field=models.TextField(blank=True, editable=False, help_text='El texto final del contrato tal como se firmó, para integridad legal.', null=True),
        ),
        migrations.AlterField(
            model_name='contratomandato',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('FINALIZADO', 'Finalizado (Pendiente de Firma)'), ('VIGENTE', 'Vigente (Firmado y Activo)'), ('TERMINADO', 'Terminado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='contratomandato',
            name='texto_final_renderizado',
            field=models.TextField(blank=True, editable=False, help_text='El texto final del contrato tal como se firmó, para integridad legal.', null=True),
        ),
    ]
