# Generated by Django 5.2.4 on 2025-08-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_arriendos', '0003_alter_contratoarrendamiento_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillacontrato',
            name='titulo',
            field=models.CharField(default=1, help_text='El título principal que aparecerá en el documento (ej: CONTRATO DE MANDATO)', max_length=255),
            preserve_default=False,
        ),
    ]
