# Generated by Django 5.2.4 on 2025-09-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_arriendos', '0004_plantillacontrato_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoarrendamiento',
            name='archivo_pdf_final',
            field=models.FileField(blank=True, help_text='El archivo PDF final que se genera al enviar a firmas.', null=True, upload_to='contratos_finales/'),
        ),
        migrations.AddField(
            model_name='contratoarrendamiento',
            name='archivo_pdf_firmado',
            field=models.FileField(blank=True, help_text='El archivo PDF final con las firmas de todas las partes.', null=True, upload_to='contratos_firmados/'),
        ),
        migrations.AddField(
            model_name='contratomandato',
            name='archivo_pdf_final',
            field=models.FileField(blank=True, help_text='El archivo PDF final que se genera al enviar a firmas.', null=True, upload_to='contratos_finales/'),
        ),
        migrations.AddField(
            model_name='contratomandato',
            name='archivo_pdf_firmado',
            field=models.FileField(blank=True, help_text='El archivo PDF final con las firmas de todas las partes.', null=True, upload_to='contratos_firmados/'),
        ),
        migrations.AlterField(
            model_name='contratoarrendamiento',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_FIRMAS', 'En Proceso de Firmas'), ('VIGENTE', 'Vigente (Firmado y Activo)'), ('TERMINADO', 'Terminado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='contratomandato',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_FIRMAS', 'En Proceso de Firmas'), ('VIGENTE', 'Vigente (Firmado y Activo)'), ('TERMINADO', 'Terminado'), ('CANCELADO', 'Cancelado')], default='BORRADOR', max_length=20),
        ),
    ]
