# Generated by Django 5.2.4 on 2025-09-02 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_inmobiliario', '0004_alter_propiedadcliente_relacion'),
        ('gestion_arriendos', '0005_contratoarrendamiento_archivo_pdf_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoarrendamiento',
            name='codeudores',
            field=models.ManyToManyField(blank=True, related_name='contratos_codeudor', to='core_inmobiliario.cliente'),
        ),
        migrations.AlterField(
            model_name='contratoarrendamiento',
            name='arrendatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_arrendatario', to='core_inmobiliario.cliente'),
        ),
    ]
