# Generated by Django 5.2.4 on 2025-10-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_arriendos', '0006_contratoarrendamiento_codeudores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoarrendamiento',
            name='es_contrato_migrado',
            field=models.BooleanField(default=False, help_text='Marcar si este contrato fue creado antes de usar el sistema (omite validaciones iniciales como captación/entrega).'),
        ),
        migrations.AddField(
            model_name='contratomandato',
            name='es_contrato_migrado',
            field=models.BooleanField(default=False, help_text='Marcar si este contrato fue creado antes de usar el sistema (omite validaciones iniciales como captación/entrega).'),
        ),
    ]
