# Generated by Django 5.2.4 on 2025-08-05 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('inmobiliaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.inmobiliaria')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('identificacion', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('direccion_correspondiencia', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('inmobiliaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.inmobiliaria')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_inmobiliaria', models.CharField(blank=True, max_length=200, null=True)),
                ('direccion', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ciudad', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ciudad_propiedad', to='core_inmobiliario.ciudad')),
                ('inmobiliaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.inmobiliaria')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PropiedadCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacion', models.CharField(choices=[('PR', 'Propietario'), ('AP', 'Apoderado'), ('AR', 'Arrendatario')], max_length=2)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_inmobiliario.cliente')),
                ('inmobiliaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.inmobiliaria')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_inmobiliario.propiedad')),
            ],
            options={
                'verbose_name': 'Propiedades y Clientes',
                'verbose_name_plural': 'Propiedades y Clientes',
            },
        ),
        migrations.AddField(
            model_name='propiedad',
            name='clientes',
            field=models.ManyToManyField(related_name='clientes_propiedad', through='core_inmobiliario.PropiedadCliente', to='core_inmobiliario.cliente'),
        ),
        migrations.CreateModel(
            name='TipoPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_propiedad', models.CharField(max_length=200)),
                ('inmobiliaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.inmobiliaria')),
            ],
            options={
                'verbose_name': 'Tipo de Propiedades',
                'verbose_name_plural': 'Tipos de Propiedades',
                'ordering': ['tipo_propiedad'],
            },
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tipo_propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='propiedad_tipo', to='core_inmobiliario.tipopropiedad'),
        ),
        migrations.AddConstraint(
            model_name='propiedadcliente',
            constraint=models.UniqueConstraint(fields=('cliente', 'propiedad', 'relacion'), name='unique_cliente_propiedad_relacion'),
        ),
        migrations.AddIndex(
            model_name='propiedad',
            index=models.Index(fields=['-created'], name='core_inmobi_created_d3a145_idx'),
        ),
    ]
