# Generated by Django 5.2.4 on 2025-08-25 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_inmobiliario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='escritura_publica',
            field=models.CharField(blank=True, help_text='Número de escritura pública, fecha de expedición, notaría y ciudad', max_length=200),
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_banco', models.CharField(max_length=200)),
                ('tipo_cuenta', models.CharField(choices=[('AHORROS', 'Ahorros'), ('CORRIENTE', 'Corriente')], max_length=20)),
                ('numero_cuenta', models.CharField(max_length=50)),
                ('nombre_titular', models.CharField(blank=True, max_length=255)),
                ('identificacion_titular', models.CharField(blank=True, max_length=50)),
                ('es_predeterminada', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_bancarias', to='core_inmobiliario.cliente')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
            },
        ),
    ]
