# Generated by Django 5.2.4 on 2025-09-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_inmobiliario', '0002_propiedad_escritura_publica_cuentabancaria'),
        ('usuarios', '0003_inmobiliaria_camara_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='identificacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('identificacion', 'inmobiliaria'), name='unique_identificacion_inmobiliaria'),
        ),
    ]
