# Generated by Django 5.2.4 on 2025-09-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_inmobiliario', '0003_alter_cliente_identificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedadcliente',
            name='relacion',
            field=models.CharField(choices=[('PR', 'Propietario'), ('AP', 'Apoderado'), ('AR', 'Arrendatario'), ('CO', 'Codeudor')], max_length=2),
        ),
    ]
